#!/usr/bin/env python3
"""Export a brand-identity palette.json to developer and designer formats.

Formats (--formats, comma-separated; default all):
  css        tokens.css         :root (scales, brand, light roles) + [data-theme="dark"] + prefers-color-scheme dark
  scss       tokens.scss        $bi-* variables and Sass maps per scale and per mode
  tailwind   tailwind.palette.js  Tailwind preset: scales + roles as var(--bi-*) references (load tokens.css too)
  dtcg       tokens.dtcg.json   W3C Design Tokens (2025.10 colour value objects; roles alias scale steps);
                                --dtcg-per-mode adds tokens.light.tokens.json + tokens.dark.tokens.json
  gpl        palette.gpl        GIMP / Inkscape / Krita palette
  swatches   swatches.html      printable swatch sheet: hex, rgb, oklch, Lab D50, contrast, light/dark role preview
CSS custom properties are --bi-<kebab-case role> (e.g. --bi-on-primary) and --bi-<scale>-<step> (--bi-primary-600).

Usage:
  python3 scripts/export_tokens.py palette.json --out tokens/
  python3 scripts/export_tokens.py palette.json --out tokens/ --formats css,tailwind
  python3 scripts/export_tokens.py palette.json --out kit/ --formats swatches --json   # list written files as JSON
  python3 scripts/export_tokens.py palette.json --out tokens/ --formats dtcg --dtcg-per-mode   # + one file per mode
Output: stdout is a short summary (<= 1.2 KB: what was exported, the output folder, the file names). --full lists
every written path, one per line; --json prints them as a JSON list. Problems go to stderr.
"""
import argparse
import html
import json
import os
import re
import sys

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import colorlib as cl  # noqa: E402

FORMATS = ("css", "scss", "tailwind", "dtcg", "gpl", "swatches")
FILENAMES = {"css": "tokens.css", "scss": "tokens.scss", "tailwind": "tailwind.palette.js",
             "dtcg": "tokens.dtcg.json", "gpl": "palette.gpl", "swatches": "swatches.html"}
HEADER = "Generated by brand-identity export_tokens.py from palette.json. Edit the palette, not this file."


def kebab(name):
    return re.sub(r"(?<=[a-z0-9])([A-Z])", r"-\1", name).lower()


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", str(name).lower()).strip("-") or "x"


def one_line(value):
    """Free-form name on one line (CR/LF and Unicode line separators become spaces)."""
    return " ".join(str(value).splitlines())


def comment_label(value):
    """Keep free-form names inside one generated CSS/SCSS/JS comment."""
    return one_line(value).replace("*/", "* /")


def scale_items(pal):
    for name, sc in (pal.get("scales") or {}).items():
        steps = sc.get("steps") or {}
        for k in cl.STEP_KEYS:
            if k in steps:
                yield slug(name), k, steps[k]


def role_items(pal, mode):
    roles = (pal.get("modes") or {}).get(mode) or {}
    for k in cl.ROLE_KEYS:
        if k in roles:
            yield k, roles[k]


def ext_items(pal, mode):
    """Extended colours as token pairs: ("ext-1", hex), ("on-ext-1", text colour); dark mode uses `dark`."""
    for e in pal.get("extended") or []:
        src = e if mode == "light" else (e.get("dark") or {})
        if src.get("hex"):
            yield e["id"], src["hex"], e.get("name") or e["id"]
        if src.get("on"):
            yield f"on-{e['id']}", src["on"], f"text on {e.get('name') or e['id']}"


def brand_items(pal):
    for b in pal.get("brand") or []:
        yield slug(b["id"]), b["hex"], b.get("name") or b["id"]


# ----------------------------------------------------------------------------- css / scss / tailwind

def to_css(pal):
    out = [f"/* brand-identity tokens: {comment_label(pal['name'])}. {HEADER} */", ":root {", "  color-scheme: light;"]
    for bid, hx, nm in brand_items(pal):
        out.append(f"  --bi-{bid}: {hx}; /* {comment_label(nm)} */")
    for sc, k, hx in scale_items(pal):
        out.append(f"  --bi-{sc}-{k}: {hx};")
    for role, hx in role_items(pal, "light"):
        out.append(f"  --bi-{kebab(role)}: {hx};")
    for name, hx, nm in ext_items(pal, "light"):
        out.append(f"  --bi-{name}: {hx}; /* {comment_label(nm)} */")
    out.append("}")
    dark = [f"    --bi-{kebab(role)}: {hx};" for role, hx in role_items(pal, "dark")]
    dark += [f"    --bi-{name}: {hx};" for name, hx, nm in ext_items(pal, "dark")]
    if dark:
        out += ["", '[data-theme="dark"] {', "  color-scheme: dark;"] + [d[2:] for d in dark] + ["}", "",
                "@media (prefers-color-scheme: dark) {", '  :root:not([data-theme="light"]) {',
                "    color-scheme: dark;"] + dark + ["  }", "}"]
    return "\n".join(out) + "\n"


def to_scss(pal):
    out = [f"// brand-identity tokens: {comment_label(pal['name'])}. {HEADER}", ""]
    for bid, hx, nm in brand_items(pal):
        out.append(f"$bi-{bid}: {hx}; // {comment_label(nm)}")
    out.append("")
    scales = {}
    for sc, k, hx in scale_items(pal):
        out.append(f"$bi-{sc}-{k}: {hx};")
        scales.setdefault(sc, []).append((k, hx))
    out.append("")
    for sc, items in scales.items():
        out.append(f"$bi-{sc}: (" + ", ".join(f"{k}: {hx}" for k, hx in items) + ");")
    for mode in ("light", "dark"):
        items = list(role_items(pal, mode))
        if items:
            out += ["", f"$bi-roles-{mode}: ("] + [f"  {kebab(r)}: {hx}," for r, hx in items] + [");"]
    ext_light = list(ext_items(pal, "light"))
    if ext_light:
        out.append("")
        out += [f"$bi-{name}: {hx}; // {comment_label(nm)}" for name, hx, nm in ext_light]
        for mode in ("light", "dark"):
            out += ["", f"$bi-extended-{mode}: ("] + [f"  {name}: {hx}," for name, hx, _ in ext_items(pal, mode)] \
                + [");"]
    return "\n".join(out) + "\n"


def to_tailwind(pal):
    lines = [f"/** brand-identity Tailwind preset: {comment_label(pal['name'])}. {HEADER}",
             " * Values are CSS variables from tokens.css, so light/dark switch without rebuilding.",
             " * Tailwind v3: module.exports = { presets: [require('./tailwind.palette.js')], ... }",
             " * Tailwind v4: @config \"./tailwind.palette.js\"; (or map the --bi-* variables in @theme). */",
             "module.exports = {", "  theme: {", "    extend: {", "      colors: {"]
    scales = {}
    for sc, k, hx in scale_items(pal):
        scales.setdefault(sc, []).append(k)
    roles = [kebab(role) for role, hx in role_items(pal, "light")] + [n for n, _, _ in ext_items(pal, "light")]
    for sc, keys in scales.items():
        lines.append(f"        '{sc}': {{")
        if sc in roles:   # role and scale share a name: bg-primary = the role, bg-primary-600 = the step
            lines.append(f"          DEFAULT: 'var(--bi-{sc})',")
        lines += [f"          {k}: 'var(--bi-{sc}-{k})'," for k in keys]
        lines.append("        },")
    for bid, hx, nm in brand_items(pal):
        lines.append(f"        '{bid}': 'var(--bi-{bid})',")
    for role in roles:
        if role not in scales:
            lines.append(f"        '{role}': 'var(--bi-{role})',")
    lines += ["      },", "    },", "  },", "};"]
    return "\n".join(lines) + "\n"


# ----------------------------------------------------------------------------- dtcg / gpl

def dtcg_value(hx):
    r, g, b = cl.parse_color(hx)
    return {"colorSpace": "srgb", "components": [round(r, 4), round(g, 4), round(b, 4)], "hex": hx}


def to_dtcg(pal):
    color = {}
    color["brand"] = {bid: {"$type": "color", "$value": dtcg_value(hx), "$description": nm}
                      for bid, hx, nm in brand_items(pal)}
    lookup = {}
    for sc, k, hx in scale_items(pal):
        color.setdefault(sc, {})[k] = {"$type": "color", "$value": dtcg_value(hx)}
        lookup.setdefault(hx, f"{{color.{sc}.{k}}}")
    role = {}
    for mode in ("light", "dark"):
        items = list(role_items(pal, mode))
        if items:
            role[mode] = {kebab(r): {"$type": "color", "$value": lookup.get(hx) or dtcg_value(hx)} for r, hx in items}
    doc = {"$description": f"brand-identity tokens: {pal['name']}. {HEADER}", "color": color}
    if role:
        doc["role"] = role
    extended = {}
    for mode in ("light", "dark"):
        items = list(ext_items(pal, mode))
        if items:
            extended[mode] = {name: {"$type": "color", "$value": lookup.get(hx) or dtcg_value(hx), "$description": nm}
                              for name, hx, nm in items}
    if extended:
        doc["extended"] = extended
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def to_dtcg_mode(pal, mode):
    """One self-contained DTCG file per mode (Figma Variables and Tokens Studio import one file per mode): the same
    colour scales in both files, roles at the top level as `role.<kebab>` aliasing the scale steps."""
    doc = json.loads(to_dtcg(pal))
    roles = (doc.pop("role", {}) or {}).get(mode, {})
    extended = (doc.pop("extended", {}) or {}).get(mode)
    doc["$description"] = f"brand-identity tokens: {pal['name']}, {mode} mode. {HEADER}"
    doc["role"] = roles
    if extended:
        doc["extended"] = extended
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def to_gpl(pal):
    out = ["GIMP Palette", f"Name: {one_line(pal['name'])}", "Columns: 11", f"# {HEADER}"]

    def row(hx, label):
        r, g, b = (int(round(c * 255)) for c in cl.parse_color(hx))
        return f"{r:3d} {g:3d} {b:3d}\t{label}"
    for bid, hx, nm in brand_items(pal):
        out.append(row(hx, f"{bid} {one_line(nm)}"))
    for sc, k, hx in scale_items(pal):
        out.append(row(hx, f"{sc}-{k}"))
    for mode in ("light", "dark"):
        for role, hx in role_items(pal, mode):
            out.append(row(hx, f"{mode} {kebab(role)}"))
        for name, hx, nm in ext_items(pal, mode):
            out.append(row(hx, f"{mode} {name} {one_line(nm)}"))
    return "\n".join(out) + "\n"


# ----------------------------------------------------------------------------- swatches.html

def fmt_oklch(hx):
    L, C, h = cl.hex_to_oklch(hx)
    return f"oklch({L * 100:.1f}% {C:.3f} {h:.1f})"


def fmt_rgb(hx):
    r, g, b = (int(round(c * 255)) for c in cl.parse_color(hx))
    return f"rgb({r} {g} {b})"


def ink(hx):
    return "#ffffff" if cl.contrast_ratio("#ffffff", hx) >= cl.contrast_ratio("#111111", hx) else "#111111"


KEY_PAIRS = [("text", "background", 4.5), ("textMuted", "background", 4.5), ("text", "surface", 4.5),
             ("onPrimary", "primary", 4.5), ("onAccent", "accent", 4.5), ("link", "background", 4.5),
             ("focus", "background", 3.0), ("danger", "background", 3.0), ("success", "background", 3.0)]


def _strings(t):
    if t is None:
        import i18nlib
        t = i18nlib.Strings("en")
    return t


def _role(t, key):
    return t.word("role", key)


def preview(roles, mode, t=None):
    e = html.escape
    t = _strings(t)
    v = {k: roles.get(k, "#888888") for k in cl.ROLE_KEYS}
    rows = []
    for fg, bg, need in KEY_PAIRS:
        if fg in roles and bg in roles:
            r = cl.contrast_ratio(roles[fg], roles[bg])
            ok = r >= need
            rows.append(f"<tr><td>{e(_role(t, fg))} / {e(_role(t, bg))}</td><td class=mono>{t.ratio(r, 2)}</td>"
                        f"<td class='{'ok' if ok else 'bad'}'>"
                        f"{e(t('swatch.pair_pass' if ok else 'swatch.pair_fail', t=t.num(need, 1)))}</td></tr>")
    badges = "".join(f"<span class=badge style='color:{v[s]};border-color:{v[s]}'>{e(_role(t, s))}</span>"
                     for s in ("success", "warning", "danger", "info"))
    return f"""
<div class="mode" style="background:{v['background']};color:{v['text']};border-color:{v['border']}">
  <div class="mode-head"><span>{e(t(f"kit.mode.{mode}"))}</span></div>
  <div class="card" style="background:{v['surface']};border-color:{v['border']}">
    <h4 style="color:{v['text']}">{e(t("swatch.heading"))}</h4>
    <p style="color:{v['textMuted']}">{e(t("swatch.copy"))} <a style="color:{v['link']}">{e(t("swatch.link"))}</a>.</p>
    <div class="btns">
      <span class="btn" style="background:{v['primary']};color:{v['onPrimary']}">{e(_role(t, "primary"))}</span>
      <span class="btn" style="background:{v['accent']};color:{v['onAccent']}">{e(_role(t, "accent"))}</span>
      <span class="btn ghost" style="color:{v['text']};border-color:{v['border']};
        box-shadow:0 0 0 2px {v['background']},0 0 0 4px {v['focus']}">{e(t("swatch.focused"))}</span>
    </div>
    <div class="alt" style="background:{v['surfaceAlt']}">{badges}</div>
  </div>
  <table class="pairs" style="color:{v['text']}">{''.join(rows)}</table>
</div>"""


def to_swatches(pal, t=None):
    """Printable swatch sheet; labels in the document language of t (i18nlib.Strings, default English)."""
    e = html.escape
    t = _strings(t)
    brand_cards = []
    for b in pal.get("brand") or []:
        if b.get("role") == "extended":
            continue          # shown in its own section below
        hx = b["hex"]
        lab = b.get("print", {}).get("lab_d50") if isinstance(b.get("print"), dict) else None
        lab = lab or [round(x, 1) for x in cl.hex_to_lab(hx, "D50")]
        w, k = cl.contrast_ratio(hx, "#ffffff"), cl.contrast_ratio(hx, "#000000")
        brand_cards.append(f"""
<figure class="brand">
  <div class="chip" style="background:{hx};color:{ink(hx)}"><span>{e(b.get('name') or b['id'])}</span>
    {f"<em>{e(t('swatch.locked'))}</em>" if b.get('locked') else ''}</div>
  <figcaption><b class=mono>{hx}</b><span class=mono>{fmt_rgb(hx)}</span><span class=mono>{fmt_oklch(hx)}</span>
    <span class=mono>Lab D50 {lab[0]:.1f} / {lab[1]:.1f} / {lab[2]:.1f}</span>
    <span>{e(t("swatch.on_wb", w=t.ratio(w, 2), k=t.ratio(k, 2)))}</span><span class=muted>{e(b.get('usage') or '')}</span>
  </figcaption>
</figure>""")
    scale_rows = []
    for name, sc in (pal.get("scales") or {}).items():
        steps = sc.get("steps") or {}
        anchor = str(sc.get("anchor")) if sc.get("anchor") is not None else None
        cells = []
        for k in cl.STEP_KEYS:
            if k not in steps:
                continue
            hx = steps[k]
            cells.append(f"<div class='step{' anchor' if k == anchor else ''}' style='background:{hx};color:{ink(hx)}'>"
                         f"<b>{k}</b><span class=mono>{hx}</span></div>")
        note = (t("swatch.anchor", step=anchor) if anchor else
                (t("swatch.tinted", scale=t.word("scale", sc["tint_of"])) if sc.get("tint_of") else ""))
        scale_rows.append(f"<div class=scale><div class=scale-name>{e(t.word('scale', name))}<small>{e(note)}</small></div>"
                          f"<div class=steps>{''.join(cells)}</div></div>")
    ext_cards = []
    for x in pal.get("extended") or []:
        d = x.get("dark") or {}
        halves = []
        for label, fill, on in ((t("kit.mode.light"), x["hex"], x.get("on")), (t("kit.mode.dark"), d.get("hex"), d.get("on"))):
            if fill:
                ratio = f" {t.ratio(cl.contrast_ratio(on, fill), 2)}" if on else ""
                halves.append(f"<div class='ext-half' style='background:{fill};color:{on or ink(fill)}'>"
                              f"<span>{label}</span><b class=mono>{fill}</b><span class=mono>Aa{ratio}</span></div>")
        ext_cards.append(f"""
<figure class="brand">
  <div class="ext-chip">{''.join(halves)}</div>
  <figcaption><b>{e(x['id'])} · {e(x.get('name') or '')}</b><span class=mono>{fmt_rgb(x['hex'])}</span>
    <span class=mono>{fmt_oklch(x['hex'])}</span><span class=muted>{e(x.get('usage') or '')}</span></figcaption>
</figure>""")
    ext_section = (f"<h2>{e(t('swatch.extended'))}</h2>\n<section class=\"brands\">{''.join(ext_cards)}</section>"
                   if ext_cards else "")
    feels = pal.get("feels")
    if feels:
        ext_section = f"<p class=muted>{e(t('swatch.feels'))}: {e(', '.join(feels))}</p>\n" + ext_section
    modes = pal.get("modes") or {}
    previews = "".join(preview(modes[m], m, t) for m in ("light", "dark") if modes.get(m))
    audit = pal.get("audit")
    audit_line = ""
    if isinstance(audit, dict) and "counts" in audit:
        c = audit["counts"]
        audit_line = (f"<p class=audit>{e(t('swatch.audit'))}: <b>{e(t('swatch.pass' if audit.get('passed') else 'swatch.fail'))}"
                      f"</b> · {e(' · '.join(t.n(k, c.get(n, 0)) for k, n in (('swatch.gates', 'gate'), ('swatch.warns', 'warn'), ('swatch.notes', 'info'))))}</p>")
    return f"""<!doctype html>
<html lang="{e(t.html_lang)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{e(pal['name'])} {e(t("swatch.title"))}</title>
<style>
  :root {{ --ink:#16181d; --muted:#5b6170; --line:#e3e5ea; --paper:#ffffff; }}
  * {{ box-sizing:border-box; }}
  body {{ margin:0; background:var(--paper); color:var(--ink);
    font:14px/1.45 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif; }}
  main {{ max-width:1180px; margin:0 auto; padding:48px 40px 64px; }}
  header {{ display:flex; justify-content:space-between; align-items:flex-end; gap:24px;
    border-bottom:1px solid var(--line); padding-bottom:20px; margin-bottom:32px; }}
  h1 {{ font-size:34px; letter-spacing:-0.02em; margin:0; }}
  h2 {{ font-size:12px; letter-spacing:.12em; text-transform:uppercase; color:var(--muted); margin:40px 0 14px; }}
  header p {{ margin:6px 0 0; color:var(--muted); max-width:640px; }}
  .mono {{ font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:12px; }}
  .muted {{ color:var(--muted); }}
  .audit {{ margin:0; font-size:13px; color:var(--muted); white-space:nowrap; }}
  .brands {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(240px,1fr)); gap:20px; }}
  .brand {{ margin:0; border:1px solid var(--line); border-radius:14px; overflow:hidden; break-inside:avoid; }}
  .brand .chip {{ height:150px; padding:16px; display:flex; justify-content:space-between; align-items:flex-end;
    font-weight:600; font-size:16px; }}
  .brand em {{ font-style:normal; font-size:11px; letter-spacing:.08em; text-transform:uppercase; opacity:.8; }}
  .ext-chip {{ display:grid; grid-template-columns:1fr 1fr; height:120px; }}
  .ext-half {{ padding:12px; display:flex; flex-direction:column; justify-content:space-between; font-size:12px; }}
  figcaption {{ display:flex; flex-direction:column; gap:3px; padding:14px 16px; font-size:12.5px; }}
  figcaption b {{ font-size:15px; }}
  .scale {{ display:grid; grid-template-columns:120px 1fr; gap:12px; align-items:stretch; margin-bottom:8px;
    break-inside:avoid; }}
  .scale-name {{ font-weight:600; display:flex; flex-direction:column; justify-content:center; }}
  .scale-name small {{ font-weight:400; color:var(--muted); font-size:11px; }}
  .steps {{ display:grid; grid-template-columns:repeat(11,1fr); border-radius:10px; overflow:hidden; }}
  .step {{ min-height:64px; padding:8px 6px; display:flex; flex-direction:column; justify-content:space-between;
    font-size:11px; }}
  .step b {{ font-size:12px; }}
  .step .mono {{ font-size:10px; }}
  .step.anchor {{ outline:3px solid var(--ink); outline-offset:-3px; }}
  .modes {{ display:grid; grid-template-columns:1fr 1fr; gap:20px; }}
  .mode {{ border:1px solid; border-radius:16px; padding:20px; break-inside:avoid; }}
  .mode-head {{ font-size:12px; letter-spacing:.12em; text-transform:uppercase; opacity:.7; margin-bottom:12px; }}
  .card {{ border:1px solid; border-radius:12px; padding:18px; }}
  .card h4 {{ margin:0 0 6px; font-size:18px; }}
  .card p {{ margin:0 0 14px; }}
  .card a {{ text-decoration:underline; }}
  .btns {{ display:flex; gap:10px; flex-wrap:wrap; margin-bottom:14px; }}
  .btn {{ padding:9px 16px; border-radius:9px; font-weight:600; font-size:13px; border:1px solid transparent; }}
  .btn.ghost {{ background:transparent; }}
  .alt {{ border-radius:9px; padding:10px; display:flex; gap:8px; flex-wrap:wrap; }}
  .badge {{ border:1.5px solid; border-radius:999px; padding:2px 10px; font-size:12px; font-weight:600; }}
  .pairs {{ width:100%; border-collapse:collapse; margin-top:14px; font-size:12px; }}
  .pairs td {{ padding:4px 0; border-top:1px solid rgba(127,127,127,.25); }}
  .pairs td:nth-child(2) {{ text-align:right; padding-right:12px; }}
  .pairs td:last-child {{ text-align:right; width:70px; }}
  .ok {{ opacity:.75; }}
  .bad {{ color:#c4001a; font-weight:700; background:#fff; border-radius:4px; }}
  @media (max-width:760px) {{ main {{ padding:28px 16px; }} .modes {{ grid-template-columns:1fr; }}
    .scale {{ grid-template-columns:1fr; }} .step .mono {{ display:none; }} header {{ flex-direction:column;
    align-items:flex-start; }} }}
  @media print {{ main {{ padding:0; }} body {{ -webkit-print-color-adjust:exact; print-color-adjust:exact; }} }}
</style></head>
<body><main>
<header><div><h1>{e(pal['name'])}</h1><p>{e(pal.get('direction') or '')}</p></div>{audit_line}</header>
<h2>{e(t("swatch.brand"))}</h2>
<section class="brands">{''.join(brand_cards)}</section>
{ext_section}
<h2>{e(t("swatch.scales"))}</h2>
<section>{''.join(scale_rows)}</section>
<h2>{e(t("swatch.roles"))}</h2>
<section class="modes">{previews}</section>
<p class="muted" style="margin-top:32px;font-size:12px">{e(t("swatch.note"))} {e(t("swatch.generated"))}</p>
</main></body></html>
"""


WRITERS = {"css": to_css, "scss": to_scss, "tailwind": to_tailwind, "dtcg": to_dtcg, "gpl": to_gpl,
           "swatches": to_swatches}


def export(pal, out_dir, formats, dtcg_per_mode=False):
    os.makedirs(out_dir, exist_ok=True)
    jobs = [(FILENAMES[f], WRITERS[f]) for f in formats]
    if dtcg_per_mode:
        jobs += [(f"tokens.{m}.tokens.json", lambda p, m=m: to_dtcg_mode(p, m)) for m in ("light", "dark")
                 if (pal.get("modes") or {}).get(m)]
    written = []
    for name, writer in jobs:
        path = os.path.join(out_dir, name)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(writer(pal))
        written.append(path)
    return written


def main(argv=None):
    cl.setup_utf8_console()
    ap = argparse.ArgumentParser(description="Export palette.json to CSS, SCSS, Tailwind, DTCG, GPL and a swatch "
                                             "sheet.", epilog="examples:" + __doc__.split("Usage:")[1],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("palette", help="palette.json")
    ap.add_argument("--out", default="tokens", help="output directory (default ./tokens)")
    ap.add_argument("--formats", default=",".join(FORMATS),
                    help=f"comma-separated subset of {','.join(FORMATS)} (default: all)")
    ap.add_argument("--json", action="store_true", help="print the written files as a JSON list")
    ap.add_argument("--full", action="store_true", help="print every written path, one per line")
    ap.add_argument("--dtcg-per-mode", action="store_true",
                    help="also write tokens.light.tokens.json and tokens.dark.tokens.json (one DTCG file per mode, "
                         "the shape Figma Variables / Tokens Studio import as modes)")
    args = ap.parse_args(argv)
    formats = [f.strip() for f in args.formats.split(",") if f.strip()]
    unknown = [f for f in formats if f not in FORMATS]
    if unknown or not formats:
        print(f"error: unknown format(s) {', '.join(unknown) or '(none given)'}; choose from {', '.join(FORMATS)}",
              file=sys.stderr)
        return 2
    try:
        pal = cl.load_palette(args.palette)
    except cl.PaletteError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    written = export(pal, args.out, formats, args.dtcg_per_mode)
    if args.json:
        print(json.dumps(written))
    elif args.full:
        print("\n".join(written))
    else:
        lines = [f"exported '{pal.get('name', 'palette')}': {len(written)} file(s)",
                 "files: " + ", ".join(os.path.basename(w) for w in written),
                 "-> " + os.path.abspath(args.out)]
        sys.stdout.write(cl.clip_summary(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
